config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|uk/ do
  root to: 'pages#index'
  resources :posts do
	resources :postcomments
  end
  resources :rozklads do
  resources :predmets
  get 'rozklads/index'
  end
  
  resources :pets

  resources :prepods

  resources :infocenters

  
  resources :events
  get "/not_permission", to: "pages#NotPermission", as:"not_permission"
  get 'pages/info'
  get 'pages/abit'
  get 'pages/stud' 

end
end
 

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :predmets
	belongs_to :rozklad
end

app/models/event.rb
class Event < ApplicationRecord

	validates :etupe, inclusion: %w(Концерт Екскурсія Вистава Збори)
	validates :ecost, inclusion: %w(Безкоштовний Платний)





end

app/models/infocenter.rb
class Infocenter < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
	mount_uploader :image, ImageUploader
	validates_processing_of :image
	validate :image_size_validation
 
private
  def image_size_validation
    errors[:image] << "should be less than 2MB" if image.size > 2.megabytes
  end
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments

	validates :title, length: { in: 1..64 }
	validates :body, length: { in: 10..54000 }
	validates :title, uniqueness: true
	validates :title, presence: true

	has_attached_file :image, styles: { medium: "1368x990>", thumb: "300x180>" }, default_url: "default.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :text, presence: true
	validates :text, length: { in: 4..256 }
end

app/models/predmet.rb
class Predmet < ApplicationRecord
	belongs_to :rozklad
	belongs_to :category
end

app/models/prepod.rb
class Prepod < ApplicationRecord
	validates :name, length: { in: 1..64 }
	validates :description, length: { in: 10..5012 }
	validates :name, uniqueness: true
	validates :name, presence: true

	has_attached_file :photo, styles: { medium: "1368x990>", thumb: "300x180>" }, default_url: "default.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/rozklad.rb
class Rozklad < ApplicationRecord
	has_many :predmets
	has_many :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts
has_many :postcomments

 validates :nickname, :email, presence: true
 validates :nickname, :email, uniqueness: true
end

app/controllers/pets_controller.rb
class PetsController < InheritedResources::Base

  private

    def pet_params
      params.require(:pet).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/infocenters_helper.rb
module InfocentersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/postcomments_helper.rb
module PostcommentsHelper
end

app/helpers/predmets_helper.rb
module PredmetsHelper
end

app/helpers/prepods_helper.rb
module PrepodsHelper
end

app/helpers/rozklads_helper.rb
module RozkladsHelper
end

app/views/pets/_form.html.erb
<br>
<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
     <div class="login100-form-title" style="background-image: url('<%= asset_path('login-bg.jpg') %>');">
    <span class="login100-form-title-1">
          <%= t("new_photo") %>
        </span>
        </div>
    <div class="col-md-6 col-md-offset-3 login-box">
<%= form_for @pet, html: { multipart: true } do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
 
      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
    <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Title', required: true  %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
 <br>
  <%= button_tag( :class => "btn btn-lg btn-primary btn-block") do %>
            <i class="zmdi zmdi-check m-r-xs"></i> <%= t("save") %>
          <% end %>

<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form', pet: @pet %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<br>

<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script><script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<center><h1><%= t("gallery") %></h1></center>


<div class="gallery">

  <% @pets.each do |pet| %>
    <figure>
    <%= image_tag pet.image, alt: "" %>
    </figure>
  <%end%>

<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display:none;">
  <symbol id="close" viewBox="0 0 18 18">
    <path fill-rule="evenodd" clip-rule="evenodd" fill="#FFFFFF" d="M9,0.493C4.302,0.493,0.493,4.302,0.493,9S4.302,17.507,9,17.507
      S17.507,13.698,17.507,9S13.698,0.493,9,0.493z M12.491,11.491c0.292,0.296,0.292,0.773,0,1.068c-0.293,0.295-0.767,0.295-1.059,0
      l-2.435-2.457L6.564,12.56c-0.292,0.295-0.766,0.295-1.058,0c-0.292-0.295-0.292-0.772,0-1.068L7.94,9.035L5.435,6.507
      c-0.292-0.295-0.292-0.773,0-1.068c0.293-0.295,0.766-0.295,1.059,0l2.504,2.528l2.505-2.528c0.292-0.295,0.767-0.295,1.059,0
      s0.292,0.773,0,1.068l-2.505,2.528L12.491,11.491z"/>
  </symbol>
</svg>

<script >popup = {
  init: function(){
    $('figure').click(function(){
      popup.open($(this));
    });
    
    $(document).on('click', '.popup img', function(){
      return false;
    }).on('click', '.popup', function(){
      popup.close();
    })
  },
  open: function($figure) {
    $('.gallery').addClass('pop');
    $popup = $('<div class="popup" />').appendTo($('body'));
    $fig = $figure.clone().appendTo($('.popup'));
    $bg = $('<div class="bg" />').appendTo($('.popup'));
    $close = $('<div class="close"><svg><use xlink:href="#close"></use></svg></div>').appendTo($fig);
    $shadow = $('<div class="shadow" />').appendTo($fig);
    src = $('img', $fig).attr('src');
    $shadow.css({backgroundImage: 'url(' + src + ')'});
    $bg.css({backgroundImage: 'url(' + src + ')'});
    setTimeout(function(){
      $('.popup').addClass('pop');
    }, 10);
  },
  close: function(){
    $('.gallery, .popup').removeClass('pop');
    setTimeout(function(){
      $('.popup').remove()
    }, 100);
  }
}

popup.init()

//# sourceURL=pen.js
</script>

app/views/pets/new.html.erb
<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<br>
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <p><%= image_tag @pet.image.url %></p>
</p>
 
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>
  
<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>