config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|uk/ do
  root to: 'pages#index'
  resources :posts do
	resources :postcomments
  end
  resources :rozklads do
  resources :predmets
  get 'rozklads/index'
  end
  
  resources :pets

  resources :prepods

  resources :infocenters

  
  resources :events
  get "/not_permission", to: "pages#NotPermission", as:"not_permission"
  get 'pages/info'
  get 'pages/abit'
  get 'pages/stud' 

end
end
 

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :predmets
	belongs_to :rozklad
end

app/models/event.rb
class Event < ApplicationRecord

	validates :etupe, inclusion: %w(Концерт Екскурсія Вистава Збори)
	validates :ecost, inclusion: %w(Безкоштовний Платний)





end

app/models/infocenter.rb
class Infocenter < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
	mount_uploader :image, ImageUploader
	validates_processing_of :image
	validate :image_size_validation
 
private
  def image_size_validation
    errors[:image] << "should be less than 2MB" if image.size > 2.megabytes
  end
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments

	validates :title, length: { in: 1..64 }
	validates :body, length: { in: 10..54000 }
	validates :title, uniqueness: true
	validates :title, presence: true

	has_attached_file :image, styles: { medium: "1368x990>", thumb: "300x180>" }, default_url: "default.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :text, presence: true
	validates :text, length: { in: 4..256 }
end

app/models/predmet.rb
class Predmet < ApplicationRecord
	belongs_to :rozklad
	belongs_to :category
end

app/models/prepod.rb
class Prepod < ApplicationRecord
	validates :name, length: { in: 1..64 }
	validates :description, length: { in: 10..5012 }
	validates :name, uniqueness: true
	validates :name, presence: true

	has_attached_file :photo, styles: { medium: "1368x990>", thumb: "300x180>" }, default_url: "default.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/rozklad.rb
class Rozklad < ApplicationRecord
	has_many :predmets
	has_many :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts
has_many :postcomments

 validates :nickname, :email, presence: true
 validates :nickname, :email, uniqueness: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, except:[:show, :index, :events]
  	before_action :set_event, except:[:new,:create,:index]

  def index
  	@events = Event.all.order(created_at: :DESC)
  end

def new
    if current_user.admin
      @event = Event.new
    else
      redirect_to not_permission_path
    end
  end 

  def create
  	@event = Event.create(event_params)
  	if @event.save
  		redirect_to root_path
  	else
  		render 'new'
  	end

  end
  
  def destroy
  	@event.destroy
  	redirect_to root_path
  end

  def edit
    if current_user.admin

    else
      redirect_to not_permission_path
    end
  end

  def update
  	@event.update(event_params)
  	redirect_to event_path
  end

  private
  	def event_params
  		params.require(:event).permit(:etitle,:edate,:etime,:venue,:venume_det,:etupe,:ecost,:einfo)
	
  	end

  	def set_event
  		@event = Event.find(params[:id])
  	end
end

app/controllers/pets_controller.rb
class PetsController < InheritedResources::Base

  private

    def pet_params
      params.require(:pet).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/infocenters_helper.rb
module InfocentersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/predmets_helper.rb
module PredmetsHelper
end

app/helpers/prepods_helper.rb
module PrepodsHelper
end

app/helpers/rozklads_helper.rb
module RozkladsHelper
end

app/views/events/_form.html.erb
	<%= f.text_field :etitle, autofocus: true, class: 'form-control', placeholder: 'Event name', required: true %>
	<br/>
	<p><%= f.label "Data" %></p>
	<%= date_select("event", "edate", start_year: 2018, end_year: 2088, order: [:day, :month, :year]) %><br />
	<br/>
	<p><%= f.label "Time" %></p>
	<%= time_select("event", "etime") %><br />
	<br/>
	<%= f.text_field :venue, autofocus: true, class: 'form-control', placeholder: 'Addres', required: true  %>
	<br/>
	<%= f.text_field :venume_det, autofocus: true, class: 'form-control', placeholder: 'Name institution', required: true  %>
	<br/>
	<p><%= f.label "Тип" %></p>
	<%= f.select :etupe, ['Концерт','Екскурсія','Вистава','Збори'] %><br />
	<br/>
	<p><%= f.label "Вхід" %></p>
	<%= f.select :ecost, ['Безкоштовний','Платний'] %><br />
	<br/>
	<p><%= f.label "Інформація" %></p>
	<div class="tiny"><%= f.text_area :einfo, :class => "tinymce", :rows => 10, :cols => 50 %><br/>
	<%= tinymce %></div><br/>

	<br/>
	<%= button_tag( :class => "btn btn-lg btn-primary btn-block") do %>
            <i class="zmdi zmdi-check m-r-xs"></i> <%= t("save") %>
          <% end %>

app/views/events/edit.html.erb
<br>
<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
     <div class="login100-form-title" style="background-image: url('<%= asset_path('login-bg.jpg') %>');">
    <span class="login100-form-title-1">
          <%= t("edit_events") %>
        </span>
        </div>
		<div class="col-md-6 col-md-offset-3 login-box">
<%= form_for @event, url:event_path, method: :patch,  validate: true do |f| %>
 <% if @event.errors.any?  %>
   <% @event.errors.full_messages.each do |msg| %>
   <li><%= msg%></li>
   <%end%>
   <%end%>
<%= render 'form', f:f %>
<%end%>

app/views/events/index.html.erb
<div class="container">
	<div class="row">
		<p><h3 style="font-weight: 900;">ПОДІЇ</h3></p>
		<% @events.each do |event| %>
			<div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
				<ul class="event-list">
					<li>
						<time datetime="2014-07-20">
							<span class="day"><%= event.edate.day %></span>
							<span class="month"><%= event.edate.month %></span>
							<span class="year"><%= event.edate.year %></span>
							<span class="time">ALL DAY</span>
						</time>
						<div class="info">
							<h2 class="title"><%=link_to event.etitle, event_path(event.id) %></h2>
						</div>
					</li>
			</div>
		<%end%>
	</div>
</div>

app/views/events/new.html.erb
<br>
<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
     <div class="login100-form-title" style="background-image: url('<%= asset_path('login-bg.jpg') %>');">
    <span class="login100-form-title-1">
          <%= t("new_events") %>
        </span>
        </div>
		<div class="col-md-6 col-md-offset-3 login-box">
			<center><%= form_for @event, url: events_path do |f| %>
				<% if @event.errors.any? %>
				 <% @event.errors.full_messages.each do |msg| %>
				 	<li><%=msg%></li>
				   <%end%>
				 <%end%>
				<%= render 'form', f:f%>
			<%end%></center>
		</div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<style>
</style>
<br>
<div id="ed">
    <% if current_user != nil and current_user.admin %>
            <%= link_to "Редагувати",  edit_event_path %> or
            <%= link_to "Видалити", event_path, data: {confirm: 'Точно видалити цю подію??'}, method: :delete %>
    <%end%>
<div class="container">
<p><h2><%= @event.etitle %></h2> <hr> 
<div class="row">
    <div class="col-sm6 col-md-4 col-lg-2 mt-4">
        <p style="font-weight:bold">Дата проведення:</p>
        <p style="font-weight:bold">Час проведення:</p>
        <p style="font-weight:bold">Місцезнаходження:</p>
        <p style="font-weight:bold">Місце проведення:</p>
        <p style="font-weight:bold">Тип події:</p>
        <p style="font-weight:bold">Вхід:</p>
    </div>

    <div class="col-sm6 col-md-4 col-lg-5 mt-4">
        <p><%= @event.edate.strftime('%d %b %Y') %>
        <p><%= @event.etime.strftime('%H:%M') %>
        <p><%= @event.venue %>
        <p><%= @event.venume_det %>
        <p><%= @event.etupe %>
        <p><%= @event.ecost %>
    </div>

</div>
<hr><h5><p><%= sanitize @event.einfo %></h5>
</div>
<br>