config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|uk/ do
  root to: 'pages#index'
  resources :posts do
	resources :postcomments
  end
  resources :rozklads do
  resources :predmets
  get 'rozklads/index'
  end
  
  resources :pets

  resources :prepods

  resources :infocenters

  
  resources :events
  get "/not_permission", to: "pages#NotPermission", as:"not_permission"
  get 'pages/info'
  get 'pages/abit'
  get 'pages/stud' 

end
end
 

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :predmets
	belongs_to :rozklad
end

app/models/event.rb
class Event < ApplicationRecord

	validates :etupe, inclusion: %w(Концерт Екскурсія Вистава Збори)
	validates :ecost, inclusion: %w(Безкоштовний Платний)





end

app/models/infocenter.rb
class Infocenter < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
	mount_uploader :image, ImageUploader
	validates_processing_of :image
	validate :image_size_validation
 
private
  def image_size_validation
    errors[:image] << "should be less than 2MB" if image.size > 2.megabytes
  end
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments

	validates :title, length: { in: 1..64 }
	validates :body, length: { in: 10..54000 }
	validates :title, uniqueness: true
	validates :title, presence: true

	has_attached_file :image, styles: { medium: "1368x990>", thumb: "300x180>" }, default_url: "default.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :text, presence: true
	validates :text, length: { in: 4..256 }
end

app/models/predmet.rb
class Predmet < ApplicationRecord
	belongs_to :rozklad
	belongs_to :category
end

app/models/prepod.rb
class Prepod < ApplicationRecord
	validates :name, length: { in: 1..64 }
	validates :description, length: { in: 10..5012 }
	validates :name, uniqueness: true
	validates :name, presence: true

	has_attached_file :photo, styles: { medium: "1368x990>", thumb: "300x180>" }, default_url: "default.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/rozklad.rb
class Rozklad < ApplicationRecord
	has_many :predmets
	has_many :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts
has_many :postcomments

 validates :nickname, :email, presence: true
 validates :nickname, :email, uniqueness: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except:[:show, :index]
  before_action :set_post, except:[:new,:create,:index]

  def new
    if current_user.admin
      @post = Post.new
    else
      redirect_to not_permission_path
    end
  end 

  def index
    @posts = Post.all.order(created_at: :DESC)
  end

  def show
    @post.update(visit: @post.visit+1)
    pp @post
     @posts = Post.all.order(created_at: :DESC)
     pp @posts
      @comments = Postcomment.where(post_id: @post.id).order(created_at: :DESC)
      pp @comments
  end

  def create
  	@post = current_user.posts.build(post_params)
  	if @post.save
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end
  
  def destroy
  	@post.destroy
  	redirect_to root_path
  end

  def edit
    if current_user.admin
    else
      redirect_to not_permission_path
    end
  end

  def update
  	@post.update(post_params)
  	redirect_to post_path
  end

  private
  	def post_params
  		params.require(:post).permit(:user_id,:title,:body,:image)
  	end

  	def set_post
  		@post = Post.find(params[:id])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/infocenters_helper.rb
module InfocentersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/predmets_helper.rb
module PredmetsHelper
end

app/helpers/prepods_helper.rb
module PrepodsHelper
end

app/helpers/rozklads_helper.rb
module RozkladsHelper
end

app/views/posts/_form.html.erb
  	<%= f.text_field :title, autofocus: true, class: 'form-control', placeholder: 'Title', required: true  %><br />
  	<p><%= f.label :body %></p>
	<div class="tiny"><%= f.text_area :body, :class => "tinymce", :rows => 10, :cols => 70, autofocus: true %><br/>
	<%= tinymce %><br/></div>
  	<p><%= f.label :image %></p>
  	<%= f.file_field :image %><br/>
 	<br/>
	<%= button_tag( :class => "btn btn-lg btn-primary btn-block") do %>
            <i class="zmdi zmdi-check m-r-xs"></i> <%= t("save") %>
          <% end %>

app/views/posts/edit.html.erb
<br>
<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
     <div class="login100-form-title" style="background-image: url('<%= asset_path('login-bg.jpg') %>');">
    <span class="login100-form-title-1">
          <%= t("edit_news") %>
        </span>
        </div>
		<div class="col-md-6 col-md-offset-3 login-box">
<%= form_for @post, url:post_path, method: :patch,  validate: true do |f| %>
 <% if @post.errors.any?  %>
   <% @post.errors.full_messages.each do |msg| %>
   <li><%= msg%></li>
   <%end%>
   <%end%>


<%= render 'form', f:f %>



<%end%>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
	<p><h3 style="font-weight: 900;">НОВИНИ</h3></p>
	<% @posts.each do |post| %>
	 <div class="col-sm-6 col-md-4 col-lg-3 mt-4">     
		<div class="card" style="width: 25rem;">
		  <div class="card-img-top"><%= image_tag post.image, height: '190' %></div>
		     <div class="card-block">
			    <h4 class="card-title"><%= link_to post.title, post_path(post.id) %></h4>
		     </div>
		</div>
	 </div>
	<%end%>	
	</div>
</div>
<br>

app/views/posts/new.html.erb
<br>
<div class="limiter">
  <div class="container-login100">
    <div class="wrap-login100">
     <div class="login100-form-title" style="background-image: url('<%= asset_path('login-bg.jpg') %>');">
    <span class="login100-form-title-1">
          <%= t("new_news") %>
        </span>
        </div>
		<div class="col-md-6 col-md-offset-3 login-box">

		<center><%= form_for @post, url: posts_path, validate: true do |f| %>
			<% if @post.errors.any? %>
			 <% @post.errors.full_messages.each do |msg| %>
			 	<li><%=msg%></li>
			   <%end%>
			 <%end%>
			<%= render 'form', f:f%>
		<%end%></center>
		</div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<br>
<div class="container">
	<div class="row">
		<div class="post">
		<div class="[ col-xs-12  col-sm-11 .col-md-11 .col-lg-11 ]">
			<div id="ed">
				<% if current_user != nil and current_user.admin %>
						<%= link_to "Edit",  edit_post_path %> or
						<%= link_to "Delete", post_path, data: {confirm: 'Точно видалити данний пост?'}, method: :delete %>
				<%end%>
			</div>
			<% if @post.image != 0 %>
			<center><%= image_tag @post.image(:medium), alt:"" %></center>
			<%end%>
			<center><h1><%= @post.title %></h1></center>
			<center><h6><%= @post.created_at.strftime('%b %d %Y') %></h6></center>
			<p><%= sanitize @post.body %></p>
			<p><h3 style="text-align: center;">ОСТАННІ НОВИНИ</h3></p>
			<% @posts[0..3].each do |post| %>
				<div class="[ col-xs-12  col-sm-5 .col-md-5 .col-lg-5 otn ]">
			<div class="card" style="width: 25rem;">
		  	<div class="card-img-top"><%= image_tag post.image, height: '190'%></div>
			     <div class="card-block">
				    <h4 class="card-title"><%= link_to post.title, post_path(post.id) %></h4>
			     </div>
			</div>
			 </div>
			<%end%>	
			</div>
			</div>
			<div class="[ col-xs-12  col-sm-1 .col-md-1 .col-lg-1]">
			<div class="right_block">
			 <small>
                <div class="statistics">
                    <p><span class="label label-default">Visitas <%= @post.visit %></span></p>
                    <p><span class="label label-default">Comentarios <%= @post.com %></span></p>
                </div>
                </small>
			<% @comments.each do |comment|%>
				<div class="bb">
					 Користувач <b><%= comment.user.nickname %></b> написав:</p>
					 <div class = "bord">
						<i><%= comment.text %></i>
					</div>
					<div class="time"><span class="glyphicon glyphicon-time"></span>
						<small><%= comment.created_at.strftime('%b %d, %Y') %></small>
					</div>
					<% if current_user != nil and current_user.admin %>
					<%= link_to 'Destroy', [comment.post, comment], :confirm => 'Are you sure?', method: :delete %>
					<%end%>
				</div>
				<% end %>
				<section>
				<%if current_user !=nil %>
					<%= form_for :postcomment, url: post_postcomments_path(@post.id) do |f| %>
					<% if flash[:notice] %>
					  <div class="notice"> <%= flash[:notice] %> </div>
					<% end %>

					<div class="com">
						<p><%= f.label "Коментарь" %></p>
						<%= f.text_area :text,  class: "content-field", placeholder: "Add a comment"%><br />
					 	<p><%= f.submit "Відправити" %></p>
					 </div>
					 <%end%>
				<%end%>
				</section>
				</div>
		</div>
	</div>
</div>
<br>