config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope "(:locale)", locale: /en|uk/ do
  root to: 'pages#index'
  resources :posts do
	resources :postcomments
  end
  resources :rozklads do
  resources :predmets
  get 'rozklads/index'
  end
  
  resources :pets

  resources :prepods

  resources :infocenters

  
  resources :events
  get "/not_permission", to: "pages#NotPermission", as:"not_permission"
  get 'pages/info'
  get 'pages/abit'
  get 'pages/stud' 

end
end
 

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :predmets
	belongs_to :rozklad
end

app/models/event.rb
class Event < ApplicationRecord

	validates :etupe, inclusion: %w(Концерт Екскурсія Вистава Збори)
	validates :ecost, inclusion: %w(Безкоштовний Платний)





end

app/models/infocenter.rb
class Infocenter < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
	mount_uploader :image, ImageUploader
	validates_processing_of :image
	validate :image_size_validation
 
private
  def image_size_validation
    errors[:image] << "should be less than 2MB" if image.size > 2.megabytes
  end
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :postcomments

	validates :title, length: { in: 1..64 }
	validates :body, length: { in: 10..54000 }
	validates :title, uniqueness: true
	validates :title, presence: true

	has_attached_file :image, styles: { medium: "1368x990>", thumb: "300x180>" }, default_url: "default.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/postcomment.rb
class Postcomment < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :text, presence: true
	validates :text, length: { in: 4..256 }
end

app/models/predmet.rb
class Predmet < ApplicationRecord
	belongs_to :rozklad
	belongs_to :category
end

app/models/prepod.rb
class Prepod < ApplicationRecord
	validates :name, length: { in: 1..64 }
	validates :description, length: { in: 10..5012 }
	validates :name, uniqueness: true
	validates :name, presence: true

	has_attached_file :photo, styles: { medium: "1368x990>", thumb: "300x180>" }, default_url: "default.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/rozklad.rb
class Rozklad < ApplicationRecord
	has_many :predmets
	has_many :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts
has_many :postcomments

 validates :nickname, :email, presence: true
 validates :nickname, :email, uniqueness: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/predmets_helper.rb
module PredmetsHelper
end

app/helpers/prepods_helper.rb
module PrepodsHelper
end

app/helpers/rozklads_helper.rb
module RozkladsHelper
end

app/views/layouts/_footer.html.erb
<style>
.myfooter {
  position: relative;
    padding: 40px 0 20px 0;
    background-color: #00091c;
    color: #878c94;
}

.myfooter .title-widget {
  text-align: left;
  color:#fff;
  font-size: 25px;
  font-weight: 300;
  line-height: 1;
  position: relative;
  text-transform: uppercase;
  font-family: 'Fjalla One', sans-serif;
  margin-top: 0;
  margin-right: 0;
  margin-bottom: 25px;
  margin-left: 0;
  padding-left: 28px;
}

.myfooter .title-widget::before {
    background-color: #ea5644;
    content: "";
    height: 22px;
    left: 0px;
    position: absolute;
    top: -2px;
    width: 5px;
}


.myfooter .social-icon{padding:0px;margin:0px;}
.myfooter .social-icon a{display:inline-block;color:#fff;font-size:25px;padding:5px;}
.myfooter .acount-icon a{display:block;color:#fff;font-size:18px;padding:5px;text-decoration:none;}
.myfooter .acount-icon .fa{margin-right:20px;}


.myfooter .category a {
    text-decoration: none;
    color: #fff;
    display: inline-block;
    padding: 5px 20px;
    margin: 1px;
    border-radius:4px;
    margin-top: 6px;
    background-color: black;
    border: solid 1px #fff;
}
.myfooter ul {
  font-size: 13px;
  list-style-type: none;
  margin-left: 0;
  padding-left: 0;
  margin-top: 15px;
  color: #7F8C8D;
}


.myfooter .payment{
	margin:0px;
	padding:0px;
	list-style-type:none
}
.myfooter .payment li{
	list-style-type:none
}
.myfooter .payment li a {
    text-decoration: none;
    display: inline-block;
    color: #fff;
    float: left;
    font-size: 25px;
    padding: 10px 10px;
}

.myfooter ul.social {
  list-style: none;
  display: inline;
  margin-left:0 !important;
  padding: 0;
}
.myfooter ul.social li {
  display: inline;
  margin: 0 5px;
}
.myfooter .social li:hover {
  transform: scale(1.15) rotate(360deg);
  -webkit-transform: scale(1.1) rotate(360deg);
  -moz-transform: scale(1.1) rotate(360deg);
  -ms-transform: scale(1.1) rotate(360deg);
  -o-transform: scale(1.1) rotate(360deg);
}

.category{
	color: white;
}
</style>
<footer class="myfooter">
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <h4 class="title-widget"><%= t("contact_us") %></h4>
          <span class="acount-icon">
            <a href=""><i class="fa fa-google-plus"></i><%= t("write_to_us") %></a>
            <a href="http://www.uzhnu.edu.ua/"><i class="fa fa-university"></i><%= t("UzhNU") %></a>
          </span>
        </div>
        <div class="col-sm-4">
          <h4 class="title-widget"><%= t("information_about_us") %></h4>
          <span class="acount-icon">
            <a href="/pages/info"><i class="fa fa-info" aria-hidden="true"></i><%= t("creating_a_faculty") %></a>         
          </span>
        </div>
        <div class="col-sm-4">
          <h4 class="title-widget"><%= t("university_administration") %></h4>
          <div class="category">
            <span>
            Адреса: Україна, Закарпатська обл., м. Ужгород, пл. Народна, 3<br>
            Телефон: +38 (03122) 3-33-41<br>
			Факс: +38 (03122) 3-42-02<br><br>
			Приймальна комісія:<br>
			Адреса: 88000, Україна, Закарпатська обл., м. Ужгород, вул. Університетська, 14, кімн. 228<br>
			Телефон: +38 (0312) 64-30-84, 066-5716240, 096-123-89-67
		    </span>   
          </div>
        </div>
      </div>
      <hr>
      
      <div class="row text-center"> © 2018. <%= t("department_of_international_law") %></div>
    </div> 
</footer>

app/views/layouts/_navbar.html.erb
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  

<style type="text/css">
nav {
  background-color: #00091c;
  position: fixed;
  z-index: 20;
  width: 100%;
  }

  .container-fluid a {
  text-decoration:none;
  color: white;
  }

  ul.nav li:hover ul.dropdown-menu {
  display:block;
}
  ul.nav p{
    color:white;
    font-size: 130%;
    padding: 10px;
    margin: 2px;
  }
  .btn:not(.btn-block) { width:140px;margin-bottom:10px; }

</style>

<nav>
  <div class="container-fluid">
    <div class="navbar-header">
      <%= image_tag("logo.png", height: '55', width: '75') %>
    </div>
    <ul class="nav navbar-nav">
      <%= link_to t("home"), root_path, class: "navbar-brand" %>

      <%= link_to  rozklads_path, class: "navbar-brand" do %>
      <%= t("schedule") %><%end%>
      <li class="dropdown">
        <p class="dropdown-toggle" data-toggle="dropdown" data: { no_turbolink: true } ><%= t("information") %><b class="caret"></b></p>
        <ul class="dropdown-menu">
          <li><%= link_to t("all_news"), posts_path %></a></li>
          <li><%= link_to t("all_events"), events_path %></a></li>
          <li><%= link_to t("infocenters"), infocenters_path %></a></li>
          <li><%= link_to t("gallery"), pets_path %></a></li>
          <li><%= link_to t("all_prepods"),prepods_path %></a></li>
          <li class="divider"></li>
          <li><a href="http://www.uzhnu.edu.ua/uk/cat/flaw-inter_law/sci_evolution"><%= t("kor_inf") %></a></li>
          <li class="divider"></li>
          <li><a href="http://www.uzhnu.edu.ua/uk/cat/abiturient"><%= t("entrant") %></a></li>
          <li><a href="http://www.uzhnu.edu.ua/uk/anounce/"><%= t("student") %></a></li>
        </ul>
      </li>

      <% if current_user != nil and current_user.admin %>
      <li class="dropdown">
        <p class="dropdown-toggle" data-toggle="dropdown" data: { no_turbolink: true } ><%= t("editpan") %><b class="caret"></b></p>
        <ul class="dropdown-menu">

          <li>
            <%= link_to new_infocenter_path do %>
              <i class="btn btn-success btn-md" role="button">
                <span class="fa fa-plus-circle"><%= t("new_infocenter") %>
              </i>
            <%end%>
          </li>

          <li>
            <%= link_to new_pet_path do %>
              <i class="btn btn-success btn-md" role="button">
                <span class="fa fa-plus-circle"><%= t("new_photo") %>
              </i>
            <%end%>
          </li>
          
          <li>

            <%= link_to new_post_path do %>
              <i class="btn btn-danger btn-md" role="button">
                <span class="fa fa-plus-circle"><%= t("new_news") %>
              </i>
           <%end%>
          </li>

          <li>
            <%= link_to new_event_path do %>
              <i class="btn btn-danger btn-md" role="button">
                <span class="fa fa-plus-circle"><%= t("new_events") %>
              </i>
            <%end%>
          </li>

          <li>
            <%= link_to new_rozklad_path do %>
              <i class="btn btn-info btn-md" role="button">
                <span class="fa fa-plus-circle"><%= t("new_schedule") %>
              </i>
            <%end%>
          </li>

          <li>
            <%= link_to rozklads_path do %>
              <i class="btn btn-info btn-md" role="button">
                <span class="fa fa-plus-circle"><%= t("edit_schedule") %>
              </i>
            <%end%>
          </li>

          <li>
            <%= link_to new_prepod_path do %>
              <i class="btn btn-danger btn-md" role="button">
                <span class="fa fa-plus-circle"><%= t("new_prepods") %>
              </i>
            <%end%>
          </li>
        </ul>
      <%end%>

    </ul>
    <ul class="nav navbar-nav navbar-right">
    <li>
              <% if I18n.locale == :uk %>
              <%= link_to 'EN', {locale: :en}%>
              <%else%>
              <%= link_to 'UK', {locale: :uk}%>
              <%end %>
            </li>
    <% if current_user.nil? %>
    <li class="tratata">
        <%= link_to user_session_path do %>
        <i class="glyphicon glyphicon-user"></i> <%= t("log_in") %>
        <%end%>
    </li>
      <% else %> 
    <li>
        <%= link_to destroy_user_session_path, method: :delete   do %>
        <i class="glyphicon glyphicon-log-in"></i> <%= t("logout") %>
        <%end%>
    </li>
       <% end %>
       
    </ul>

  </div>
</nav>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pravo</title>
    <%= csrf_meta_tags %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700&amp;subset=cyrillic" rel="stylesheet">
  </head>

  <body>
    
  <%= render 'layouts/navbar' %>
  <br>
  <div class="content-nav">

    <div class="ram">
      <div class="col-xm-3">
    <%= yield %>
    </div>
    </div></div>
  <%=render 'layouts/footer' %>
  <script>
// Animation, to disable animation for mobile please write the *mobile* in *sr* on line 3
$(document).ready(function(){
  AOS.init({ disable: 'sr' });
  $('[data-bs-hover-animate]')
    .mouseenter( function(){ var elem = $(this); elem.addClass('animated ' + elem.attr('data-bs-hover-animate')) })
    .mouseleave( function(){ var elem = $(this); elem.removeClass('animated ' + elem.attr('data-bs-hover-animate')) });
});


// Scroll effect
$(document).ready(function() {
  // navigation click actions 
  $('.scroll-link').on('click', function(event){
    event.preventDefault();
    var sectionID = $(this).attr("data-id");
    scrollToID('#' + sectionID, 750);
  });
  // scroll to top action
  $('.scroll-top').on('click', function(event) {
    event.preventDefault();
    $('html, body').animate({scrollTop:0}, 'slow');     
  });
  // mobile nav toggle
  $('#nav-toggle').on('click', function (event) {
    event.preventDefault();
    $('#main-nav').toggleClass("open");
  });
});
// scroll function
function scrollToID(id, speed){
  var offSet = 50;
  var targetOffset = $(id).offset().top - offSet;
  var mainNav = $('#main-nav');
  $('html,body').animate({scrollTop:targetOffset}, speed);
  if (mainNav.hasClass("open")) {
    mainNav.css("height", "1px").removeClass("in").addClass("collapse");
    mainNav.removeClass("open");
  }
}
if (typeof console === "undefined") {
    console = {
        log: function() { }
    };
}
  </script>
  </body>
</html>

app/views/pages/NotPermission.html.erb
<br>
У вас нема прав для данної дії!!!

app/views/pages/_block.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
  <!-- Overlay -->


  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#bs-carousel" data-slide-to="1"></li>
    <li data-target="#bs-carousel" data-slide-to="2"></li>
  </ol>
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item slides active">
      <div class="slide-1"></div>
      <div class="hero">
      <h1><%= t("department_of_international_law") %></h1>
       <div class="col-md-2 col-md-offset-5 hidden-xs">
                    <button class="btn btn-danger btn-block scroll-link" type="button" data-id="posts"><%= t("show_more") %></button>
                </div>
                <div class="col-xs-3 col-xs-offset-4 hidden-sm hidden-md hidden-lg">
                    <button class="btn btn-danger scroll-link" type="button" data-id="posts"><%= t("show_more") %></button>
                </div>  
      </div>
    </div>
    <div class="item slides">
      <div class="slide-2"></div>
      <div class="hero">  
      <h1><%= t("department_of_international_law") %></h1>
       <div class="col-md-2 col-md-offset-5 hidden-xs">
                    <button class="btn btn-danger btn-block scroll-link" type="button" data-id="posts"><%= t("show_more") %></button>
                </div>
                <div class="col-xs-3 col-xs-offset-4 hidden-sm hidden-md hidden-lg">
                    <button class="btn btn-danger scroll-link" type="button" data-id="posts"><%= t("show_more") %></button>
                </div>      
      </div>
    </div>
    <div class="item slides">
      <div class="slide-3"></div>
      <div class="hero">   
      <h1><%= t("department_of_international_law") %></h1>
       <div class="col-md-2 col-md-offset-5 hidden-xs">
                    <button class="btn btn-danger btn-block scroll-link" type="button" data-id="posts"><%= t("show_more") %></button>
                </div>
                <div class="col-xs-3 col-xs-offset-4 hidden-sm hidden-md hidden-lg">
                    <button class="btn btn-danger scroll-link" type="button" data-id="posts"><%= t("show_more") %></button>
                </div>    
      </div>
    </div>
  </div> 
</div>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.js"></script>

app/views/pages/abit.html.erb
<style>
.cool{
	padding: 20px;
	margin: 20px;
}
</style>
<div class="cool">
<br>
<center><p><h2>Інформація про кафедру</h2></p></center>
<h5><p>
Кафедра міжнародного права та міжнародних відносин створена у 1997 р. у структурі  Ужгородського державного інституту інформатики, економіки і права, який у 2004 р., реорганізований в Закарпатський державний університет IV рівня акредитації.
</p>

<p>У 2013 р. у зв’язку з  об’єднанням Закарпатського державного університету з Ужгородським національним університетом (надалі: ДВНЗ УжНУ) кафедра міжнародного права стала однойменною кафедрою ДВНЗ УжНУ. Протягом більше ніж 18 років діяльності кафедри міжнародного права, сформовано науково-педагогічний колектив фахівців, юристів-міжнародників, закладено концептуальні напрями подальшого розвитку кафедри міжнародного права, визначено актуальні напрями наукових досліджень сучасної  проблематики теорії і практики міжнародного права.</p>
<p>
Від початку створення кафедри міжнародного права її очолює професор кафедри Динис Георгій Георгійович, який з відзнакою закінчив факультет міжнародних відносин та міжнародного права Київського державного університету ім. Т. Г. Шевченка, працював на Ближньому Сході та в Африці, в наукових інститутах Академії наук України. Проводив наукові дослідження та лекції в університетах США (Джорджія, Орегон, в юридичній школі Еморі (Атланта). У 1996-1998.рр. працював в якості юридичного експерта Робочої групи Ради Європи з питань підготовки Європейських Конвенцій захисту  гірських регіонів та сільськогосподарських районів. Обирався Комітетом Міністрів Ради Європи Радником Комітету Радників Центральної та Східної Європи (Рада Європи) з питань транскордонного співробітництва (1998-2001рр.). Автор більше 60 наукових, навчально-методичних публікацій з міжнародного права, права ЄС у вітчизняних та зарубіжних виданнях.</p>
<p>
Кафедра міжнародного права ДВНЗ УжНУ має значний кадровий потенціал, який забезпечує відповідний рівень навчальної, методичної та наукової роботи. До професорсько-викладацького складу кафедри входять: 2 професори, 7 кандидатів юридичних наук захищених по спеціальності 12.00.11 – «Міжнародне право», а також  фахівці-правознавці. До навчального процесу долучаються вчені з інших вітчизняних та зарубіжних університетів.</p>
<p>
 Професорсько-викладацький склад кафедри має досвід наукової, педагогічної та юридичної практики у галузі міжнародних відносин та зовнішньої політики у міжнародних організаціях, зарубіжних інституціях, досвід захисту прав та інтересів фізичних та юридичних осіб у міжнародних судових інстанціях. Співробітники кафедри приймають участь у підготовці законопроектів та регіональних міжнародних програм з транскордонного співробітництва України,  беруть участь в роботі міжнародних конференцій та органів міжнародних організацій, виступають з циклами лекцій у вищих навчальних закладах ближнього і далекого зарубіжжя. Кафедра активно підтримує  міжнародне співробітництво з університетськими школами міжнародного права України, Угорщини, США.</p>
<p>
Пріоритетним напрямом розвитку кафедри міжнародного права визначена науково-організаційна діяльність з метою отримання нових знань та впровадження їх на практиці у  сучасний навчальний процес. Наукова комплексна кафедральна тема дослідження «Теорія і практика трансформацій сучасного міжнародного права».</p>
<p>
Кафедра міжнародного права забезпечує  підготовку конкурентоздатних   фахівців зі спеціальності «Міжнародне право», кваліфікація: юрист-міжнародник, а також  перекладач з іноземної мови, молодший науковий співробітник з міжнародного права.</p>
<p>
Фахівці з міжнародного права володіють поглибленими знаннями з міжнародного публічного права, міжнародного приватного права та права Європейського Союзу, та набувають вміння:</p>

    <p>компетентно та професійно обґрунтовувати та висловлювати свою точку зору щодо правових аспектів міжнародної діяльності та державного управління України, включаючи: проблематики міжнародного права, національного законодавства та законодавства інших держав, діяльності міністерства закордонних справ, дипломатичних та консульських місій за кордоном або при міжнародних організаціях, зокрема проблематики міжнародного права та національного законодавства;</p>
    <p>використовувати юридичні поняття та категорії, що застосовуються для надання правової допомоги, а також у сфері юстиції та правосуддя; викладати міжнародно-правові та національно-правові дисципліни у вищих навчальних закладах та оперувати основами міжнародно-правового аналізу зовнішньополітичних та зовнішньоекономічних проблем.</p>

<p>Випускник (юрист-міжнародник) здатний самостійно аналізувати та досліджувати актуальну проблематику міжнародного права, фахово готувати аналітичні матеріали,  рекомендації, експертні висновки для органів державної влади та приватних осіб з проблематики міжнародного та національного права, представляти інтереси України в міжнародних організаціях, представляти інтереси України та її громадян в міжнародних та національних судових установах, працювати в  різних юридичних інституціях, міжнародних компаніях.
</p></h5>
</div>

app/views/pages/index.html.erb
<%= render "pages/block" %>
<div class="container">
	<div class="row">
	<section id="posts">
		<div class="col-sm-6 col-md-8 col-lg-9 mt-4">  
		<h3 style="font-weight: 900;"><%= t("news") %> |<i class="link"> <%= link_to t("all_news"), posts_path %></i></h3>

		<% @posts[0..2].each do |post| %>
		    <div class="col-sm-6 col-md-8 col-lg-4 mt-9">
			<div class="card" style="width: 25rem;">
			  <div class="card-img-top"><%= image_tag post.image, height: '190' %></div>
			     <div class="card-block">
				    <h4 class="card-title"><%= link_to post.title, post_path(post.id) %></h4>
			     </div>
			</div>
		 	</div>
		<%end%>	
		</div>
	</section>
		
	<section id="events">	
		<div class="[ col-sm-6 col-md-4 col-lg-2 mt-4]">
		<h3 style="font-weight: 900;"><%= t("events") %> | <i class="link"><%= link_to t("all_events"), events_path %></i></h3>
		<% @events[0..2].each do |event| %>
				<ul class="event-list">
					<li>
						<time datetime="12-20">
							<span class="day"><%= event.edate.day %></span>
							<span class="month"><%= event.edate.month %></span>
						</time>
						<div class="info">
							<h2 class="title"><%= link_to event.etitle, event_path(event.id) %></h2>
						</div>
					</li>
				</ul>
		<%end%>
		</div>
	</section>
	</div>
</div>
<br>
<div class="gallerya">
<br>
<div class="container">
<p><h3 style="font-weight: 900; margin-left: 65px;"><%= t("gallery") %> | <i class="link"><%= link_to t("all_photo"), pets_path %></i></h3></p>
  <%= link_to pets_path do %>
<div class="gallery">
  <% @pets[0..2].each do |pet| %>
    <figure>
    <%= image_tag pet.image,height: '244', width: '255', alt: "" %>
    </figure>
  <%end%>
</div>
<%end%>